#ifndef __RTK_INTERFACE_H__
#define __RTK_INTERFACE_H__

#ifndef CONFIG_RTL_ALIASNAME
#define ALIASNAME_VC   "vc"
#define ALIASNAME_BR   "br"
#define ALIASNAME_NAS  "nas"
#define ALIASNAME_DSL  "dsl"
#define ALIASNAME_ETH  "eth"
#define ALIASNAME_WLAN "wlan"
#define ALIASNAME_PPP  "ppp"
#define ALIASNAME_MWNAS  "nas0_"
#define ALIASNAME_ELAN_PREFIX  "eth0."
#define ALIASNAME_PTM  "ptm"
#define ALIASNAME_MWPTM  "ptm0_"
#define ORIGINATE_NUM 2

#else
#define ALIASNAME_VC   CONFIG_ALIASNAME_VC//"vc"
#define ALIASNAME_BR   CONFIG_ALIASNAME_BR//"br"
#define ALIASNAME_NAS  CONFIG_ALIASNAME_NAS//"nas"
#define ALIASNAME_DSL  CONFIG_ALIASNAME_DSL//"dsl"
#define ALIASNAME_ETH  CONFIG_ALIASNAME_ETH//"eth"
#define ALIASNAME_WLAN  CONFIG_ALIASNAME_WLAN//"wlan"
#define ALIASNAME_PPP  CONFIG_ALIASNAME_PPP//"ppp"
#define ALIASNAME_MWNAS  CONFIG_ALIASNAME_MWNAS//"nas0_"
#define ALIASNAME_ELAN_PREFIX  CONFIG_ALIASNAME_ELAN_PREFIX//"eth0."
#define ALIASNAME_PTM  CONFIG_ALIASNAME_PTM//"ptm"
#define ALIASNAME_MWPTM  CONFIG_ALIASNAME_MWPTM//"ptm0_"
#define ORIGINATE_NUM CONFIG_ORIGINATE_NUM

#endif

#define RTL_DEV_NAME_NUM(name,num)	name#num

#define ALIASNAME_NAS0  RTL_DEV_NAME_NUM(ALIASNAME_NAS,0)//"nas0"
#define ALIASNAME_PTM0  RTL_DEV_NAME_NUM(ALIASNAME_PTM,0)//"ptm0"

#define ALIASNAME_DSL0  RTL_DEV_NAME_NUM(ALIASNAME_DSL,0)//dsl0
#define ALIASNAME_ELAN0  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,2)
#define ALIASNAME_ELAN1  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,3)
#define ALIASNAME_ELAN2  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,4)
#define ALIASNAME_ELAN3  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,5)
#define ALIASNAME_ELAN4  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,6)
#define ALIASNAME_ELAN5  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,7)
#define ALIASNAME_ELAN6  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,8)
#define ALIASNAME_ELAN7  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,9)
#define ALIASNAME_ELAN8  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,10)
#define ALIASNAME_ELAN9  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,11)
#define ALIASNAME_ELAN10  RTL_DEV_NAME_NUM(ALIASNAME_ELAN_PREFIX,12)

#define RTL_VDEV_NAME_NUM(name,num)	name"."#num
#define ALIASNAME_VELAN0 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN0, 0)
#define ALIASNAME_VELAN1 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN1, 0)
#define ALIASNAME_VELAN2 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN2, 0)
#define ALIASNAME_VELAN3 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN3, 0)
#define ALIASNAME_VELAN4 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN4, 0)
#define ALIASNAME_VELAN5 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN5, 0)
#define ALIASNAME_VELAN6 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN6, 0)
#define ALIASNAME_VELAN7 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN7, 0)
#define ALIASNAME_VELAN8 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN8, 0)
#define ALIASNAME_VELAN9 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN9, 0)
#define ALIASNAME_VELAN10 RTL_VDEV_NAME_NUM(ALIASNAME_ELAN10, 0)

#ifdef CONFIG_USER_SUPPORT_EXTERNAL_SWITCH
#define ALIASNAME_EXTELAN_PREFIX  "ext0."
#define ALIASNAME_EXTELAN0  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,2)
#define ALIASNAME_EXTELAN1  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,3)
#define ALIASNAME_EXTELAN2  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,4)
#define ALIASNAME_EXTELAN3  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,5)
#define ALIASNAME_EXTELAN4  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,6)
#define ALIASNAME_EXTELAN5  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,7)
#define ALIASNAME_EXTELAN6  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,8)
#define ALIASNAME_EXTELAN7  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,9)
#define ALIASNAME_EXTELAN8  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,10)
#define ALIASNAME_EXTELAN9  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,11)
#define ALIASNAME_EXTELAN10  RTL_DEV_NAME_NUM(ALIASNAME_EXTELAN_PREFIX,12)
#endif

#define ALIASNAME_BR0   RTL_DEV_NAME_NUM(ALIASNAME_BR,0)//"br0"
#define ALIASNAME_WLAN0  RTL_DEV_NAME_NUM(ALIASNAME_WLAN,0)//"wlan0"

#define ALIASNAME_VAP   "-vap" //must include '-' at fast
#define ALIASNAME_WLAN0_VAP  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0,-vap)//"wlan0-vap"

#define ALIASNAME_WLAN0_VAP0  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,0)//"wlan0-vap0"
#define ALIASNAME_WLAN0_VAP1  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,1)//"wlan0-vap1"
#define ALIASNAME_WLAN0_VAP2  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,2)//"wlan0-vap2"
#define ALIASNAME_WLAN0_VAP3  RTL_DEV_NAME_NUM(ALIASNAME_WLAN0_VAP,3)//"wlan0-vap3"

#define WANMODE_CONF_STR "WAN Mode"
#define PON_CONF_STR "PON WAN"
#define ETHWAN_CONF_STR "Ethernet WAN"
#define PTMWAN_CONF_STR "PTM WAN"
#ifdef WLAN_WISP
#define WLWAN_CONF_STR "Wireless WAN"
#endif
#ifdef CONFIG_VDSL
#define DSLWAN_CONF_STR "ATM WAN"
#define ADSL_SETTINGS_STR "DSL Settings"
#define ADSL_STR "DSL"
#define ADSL_TONE_STR "DSL Tone"
#define ADSL_SLV_STR "DSL Slave"
#define ADSL_SLV_TONE_STR "DSL Slave Tone"
#else
#define DSLWAN_CONF_STR "DSL WAN"
#define ADSL_SETTINGS_STR "ADSL Settings"
#define ADSL_STR "ADSL"
#define ADSL_TONE_STR "ADSL Tone"
#define ADSL_SLV_STR "ADSL Slave"
#define ADSL_SLV_TONE_STR "ADSL Slave Tone"
#endif /*CONFIG_VDSL*/
#define ATM_SETTINGS_STR "ATM Settings"
#define ATM_LOOPBACK_STR "ATM Loopback"
#define ADSL_CONNECTION_STR "ADSL Connection"
#ifdef CONFIG_DSL_VTUO
#define VTUO_SETTINGS_STR "VTU-O DSL Settings"
#define VTUO_STATUS_STR "VTU-O DSL"
#endif /*CONFIG_DSL_VTUO*/


extern const char*  wlan[];
extern const char*  wlan_itf[];
extern const int  wlan_en[];

#ifdef WLAN_8_SSID_SUPPORT
typedef enum MARK
{
	PMAP_ETH0_SW0 = 0,
	PMAP_ETH0_SW1,
	PMAP_ETH0_SW2,
#ifdef CONFIG_RTL_MULTI_PHY_ETH_WAN
	PMAP_ETH0_SW3=CONFIG_LAN_PORT_NUM,
#else
	PMAP_ETH0_SW3,
#endif
	PMAP_WLAN0,
	PMAP_WLAN0_VAP0,
	PMAP_WLAN0_VAP1,
	PMAP_WLAN0_VAP2,
	PMAP_WLAN0_VAP3,
	PMAP_WLAN0_VAP4,
	PMAP_WLAN0_VAP5,
	PMAP_WLAN0_VAP6,
	PMAP_WLAN1,
	PMAP_WLAN1_VAP0,
	PMAP_WLAN1_VAP1,
	PMAP_WLAN1_VAP2,
	PMAP_WLAN1_VAP3,
	PMAP_WLAN1_VAP4,
	PMAP_WLAN1_VAP5,
	PMAP_WLAN1_VAP6,
	PMAP_ITF_END
} PMAP_LAN_T;
#else
typedef enum MARK
{
	PMAP_ETH0_SW0 = 0,
	PMAP_ETH0_SW1,
	PMAP_ETH0_SW2,
#ifdef CONFIG_RTL_MULTI_PHY_ETH_WAN
	PMAP_ETH0_SW3=CONFIG_LAN_PORT_NUM,
#else
	PMAP_ETH0_SW3,
#endif
	PMAP_WLAN0,
	PMAP_WLAN0_VAP0,
	PMAP_WLAN0_VAP1,
	PMAP_WLAN0_VAP2,
	PMAP_WLAN0_VAP3,
	PMAP_WLAN1,
	PMAP_WLAN1_VAP0,
	PMAP_WLAN1_VAP1,
	PMAP_WLAN1_VAP2,
	PMAP_WLAN1_VAP3,
#if defined(CONFIG_RTK_DEV_AP)
	PMAP_WLAN2,
	PMAP_WLAN2_VAP0,
	PMAP_WLAN2_VAP1,
	PMAP_WLAN2_VAP2,
	PMAP_WLAN2_VAP3,
#endif
	PMAP_ITF_END
} PMAP_LAN_T;
#endif

#ifdef WLAN_8_SSID_SUPPORT
#define PMAP_WLAN0_VAP_END PMAP_WLAN0_VAP6
#define PMAP_WLAN1_VAP_END PMAP_WLAN1_VAP6
#else
#define PMAP_WLAN0_VAP_END PMAP_WLAN0_VAP3
#define PMAP_WLAN1_VAP_END PMAP_WLAN1_VAP3
#endif


#ifdef IP_PASSTHROUGH
extern const char LAN_IPPT[];	// alias for IP passthrough
#endif
extern const char ELANIF[];
#ifdef CONFIG_RTL_MULTI_LAN_DEV
#ifdef CONFIG_RTL9601B_SERIES
#define ELANVIF_NUM 1//eth lan virtual interface number
#else
#ifdef CONFIG_RTL_MULTI_PHY_ETH_WAN
#define ELANVIF_NUM (CONFIG_LAN_PORT_NUM+1) //eth lan virtual interface number
#else
#define ELANVIF_NUM CONFIG_LAN_PORT_NUM//eth lan virtual interface number
#endif
#endif
#else
#define ELANVIF_NUM 1
#endif
//#if defined(CONFIG_ETHWAN) || defined(CONFIG_RTL_MULTI_LAN_DEV)
extern const char* ELANRIF[];
#ifdef CONFIG_USER_SUPPORT_EXTERNAL_SWITCH
extern const char* EXTELANRIF[];
#endif
extern const char* ELANVIF[];
extern const char* SW_LAN_PORT_IF[];
extern const char BRIF[];
//#endif

#endif // __RTK_INTERFACE_H__
